name: PKI CI
on: [push, pull_request]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  ca-tests:
    needs: build
    uses: ./.github/workflows/ca-tests.yml
    with:
      repo: ${{ needs.call-build-workflow.outputs.repo }}
      db-image: ${{ needs.call-build-workflow.outputs.db-image }}

  ca-tests2:
    needs: build
    uses: ./.github/workflows/ca-tests2.yml
    with:
      repo: ${{ needs.call-build-workflow.outputs.repo }}
      db-image: ${{ needs.call-build-workflow.outputs.db-image }}

  kra-tests:
    needs: build
    uses: ./.github/workflows/kra-tests.yml
    with:
      db-image: ${{ needs.call-build-workflow.outputs.db-image }}

  ocsp-tests:
    needs: build
    uses: ./.github/workflows/ocsp-tests.yml
    with:
      db-image: ${{ needs.call-build-workflow.outputs.db-image }}

  tools-tests:
    needs: build
    uses: ./.github/workflows/tools-tests.yml
